CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE folders (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  parent_id UUID REFERENCES folders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE NULLS NOT DISTINCT (name, parent_id, user_id)
);

CREATE TABLE files (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  mimetype VARCHAR(100) NOT NULL,
  size BIGINT NOT NULL CHECK (size > 0),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  folder_id UUID REFERENCES folders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE (name, folder_id)
);

CREATE OR REPLACE FUNCTION create_root_folder()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
AS $$
BEGIN
  INSERT INTO folders (name, user_id, parent_id) 
  VALUES ('root', NEW.id, NULL);

  RETURN NULL;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_create_root_folder
  AFTER INSERT
  ON users
  FOR EACH ROW
    EXECUTE FUNCTION create_root_folder()